const ActionTypes = {
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',

  UPDATE_VIDEO_WIDTH: 'UPDATE_VIDEO_WIDTH',

  UPDATE_DECK_VALUE: 'UPDATE_DECK_VALUE',
  UPDATE_DECK_LABEL: 'UPDATE_DECK_LABEL',

};

export default ActionTypes;
